<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-08-20 14:08:44                         *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class ProtoFeatureType extends AutoProtoFeatureType
	{
		const BOOLEAN	= 1;
		const INTEGER	= 2;
		const INT_RANGE	= 3;
	}
?>