<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-09-11 16:00:25                         *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoMailQueueDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'mail_queue';
		}
		
		public function getObjectName()
		{
			return 'MailQueue';
		}
		
		public function getSequence()
		{
			return 'mail_queue_id';
		}
	}
?>