<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-08-20 14:08:44                         *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoFeatureTypeDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'feature_type';
		}
		
		public function getObjectName()
		{
			return 'FeatureType';
		}
		
		public function getSequence()
		{
			return 'feature_type_id';
		}
	}
?>