<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2012-07-28 23:35:44                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCityDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'city';
		}
		
		public function getObjectName()
		{
			return 'City';
		}
		
		public function getSequence()
		{
			return 'city_id';
		}
	}
?>