<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2012-07-28 23:35:44                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class CityDAO extends AutoCityDAO
	{
		// last chance for customization
	}
?>