<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-09-11 16:00:25                         *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class MailQueueDAO extends AutoMailQueueDAO
	{
		// last chance for customization
	}
?>