<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-07-16 11:28:06                         *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class PropertyPicturesDAO extends OneToManyLinked
	{
		public function __construct(Property $property, $lazy = false)
		{
			parent::__construct(
				$property,
				Picture::dao(),
				$lazy
			);
		}
		
		/**
		 * @return PropertyPicturesDAO
		**/
		public static function create(Property $property, $lazy = false)
		{
			return new self($property, $lazy);
		}
		
		public function getParentIdField()
		{
			return 'property_id';
		}
	}
?>