<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-07-01 16:43:04                         *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class UserDAO extends AutoUserDAO
	{
		public function isUnique($email)
		{
			return null=== $this->
				getByLogicSafe(	Expression::eq('email', $email));
		}
		
		public function activate($code, $password)
		{
			$user = $this->getByLogicSafe(
				Expression::eq('code', $code)
			);
			
			if (!empty($user)) {
				$user->
					setCode(null)->
					setRole(Role::user())->
					setPassword(sha1($password))->
					setActivated(Timestamp::makeNow());
				
				$user = $this->save($user);
			}
			
			return $user;
		}
		
		public function login($login, $hash)
		{
			$user = $this->
				getByLogicSafe(
					Expression::andBlock(
						Expression::eq('email', $login),
						Expression::eq('password', $hash)
					)
				);
			
			if ($user)
				$this->updateLastLogin($user);
			
			return $user;
		}
		
		public function autoLogin($hash)
		{
			$user = $this->getByLogicSafe(Expression::eq('auto_login', $hash));
			
			if ($user)
				$this->updateLastLogin($user);
			
			return $user;
		}
		
		/**
		 * Safe getByLogic method
		 * @param LogicalChain $logic
		 * @return User or NULL
		 */
		public function getByLogicSafe(LogicalObject $logic)
		{
			try {
				return $this->getByLogic($logic);
			} catch (ObjectNotFoundException $e) {/*_*/}
			catch (TooManyRowsException $e) {/*_*/}
			
			return null;
		}
		
		/**
		 * Not sure about the method
		 * @param User $user
		 * @return User $user
		 */
		private function updateLastLogin(User $user)
		{
			return $user;
		}
	}
?>