<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-07-01 16:43:04                         *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class UserDAO extends AutoUserDAO
	{
		public function isUnique($email)
		{
			try {
				$this->getByLogic(
					Expression::eq('email', $email)
				);
			} catch (ObjectNotFoundException $e) {
				return true;
			} catch (TooManyRowsException $e) {/*_*/}
			
			return false;
		}
		
		public function activate($code, $password)
		{
			try {
				$user = $this->getByLogic(
					Expression::eq('code', $code)
				);
				
				$user->
					setCode(null)->
					setPassword(md5($password))->
					setActivated(Timestamp::makeNow());
				
				return $this->save($user);
			} catch (ObjectNotFoundException $e) {
				return null;
			} catch (TooManyRowsException $e) {
				return null;
			}
			
			return null;
		}
	}
?>