<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-07-03 10:34:48                         *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoProperty extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Property', 8, true, true, false, null, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 128, true, true, false, null, null),
				'description' => LightMetaProperty::fill(new LightMetaProperty(), 'description', null, 'string', null, 512, false, true, false, null, null),
				'user' => LightMetaProperty::fill(new LightMetaProperty(), 'user', 'user_id', 'identifier', 'User', 8, true, false, false, 1, 3),
				'price' => LightMetaProperty::fill(new LightMetaProperty(), 'price', null, 'float', null, 4, false, true, false, null, null),
				'propertyType' => LightMetaProperty::fill(new LightMetaProperty(), 'propertyType', 'property_type_id', 'enumeration', 'PropertyType', 8, true, false, false, 1, 3),
				'offerType' => LightMetaProperty::fill(new LightMetaProperty(), 'offerType', 'offer_type_id', 'enumeration', 'OfferType', 8, true, false, false, 1, 3),
				'features' => LightMetaProperty::fill(new LightMetaProperty(), 'features', 'features_id', 'identifierList', 'Feature', null, false, false, false, 2, null)
			);
		}
	}
?>