<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2012-09-03 19:16:13                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoProperty extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Property', 8, true, true, false, null, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 128, true, true, false, null, null),
				'description' => LightMetaProperty::fill(new LightMetaProperty(), 'description', null, 'string', null, 512, false, true, false, null, null),
				'user' => LightMetaProperty::fill(new LightMetaProperty(), 'user', 'user_id', 'integerIdentifier', 'User', null, true, false, false, 1, 3),
				'propertyType' => LightMetaProperty::fill(new LightMetaProperty(), 'propertyType', 'property_type_id', 'enumeration', 'PropertyType', null, true, false, false, 1, 3),
				'offerType' => LightMetaProperty::fill(new LightMetaProperty(), 'offerType', 'offer_type_id', 'enumeration', 'OfferType', null, true, false, false, 1, 3),
				'features' => LightMetaProperty::fill(new LightMetaProperty(), 'features', 'features_id', 'identifierList', 'Feature', null, false, false, false, 2, null),
				'image' => LightMetaProperty::fill(new LightMetaProperty(), 'image', 'image_id', 'integerIdentifier', 'Picture', null, false, false, false, 1, 3),
				'pictures' => LightMetaProperty::fill(new LightMetaProperty(), 'pictures', 'pictures_id', 'identifierList', 'Picture', null, false, false, false, 2, null),
				'location' => LightMetaProperty::fill(new LightMetaProperty(), 'location', 'location_id', 'integerIdentifier', 'City', null, true, false, false, 1, 3),
				'created' => LightMetaProperty::fill(new LightMetaProperty(), 'created', null, 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'published' => LightMetaProperty::fill(new LightMetaProperty(), 'published', null, 'timestamp', 'Timestamp', null, false, true, false, null, null)
			);
		}
	}
?>