<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-09-21 11:05:41                         *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoUser extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'User', 8, true, true, false, null, null),
				'name' => LightMetaProperty::fill(new LightMetaProperty(), 'name', null, 'string', null, 64, true, true, false, null, null),
				'surname' => LightMetaProperty::fill(new LightMetaProperty(), 'surname', null, 'string', null, 64, false, true, false, null, null),
				'email' => LightMetaProperty::fill(new LightMetaProperty(), 'email', null, 'string', null, 128, true, true, false, null, null),
				'password' => LightMetaProperty::fill(new LightMetaProperty(), 'password', null, 'string', null, 40, false, true, false, null, null),
				'phone' => LightMetaProperty::fill(new LightMetaProperty(), 'phone', null, 'string', null, 64, false, true, false, null, null),
				'created' => LightMetaProperty::fill(new LightMetaProperty(), 'created', null, 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'activated' => LightMetaProperty::fill(new LightMetaProperty(), 'activated', null, 'timestamp', 'Timestamp', null, false, true, false, null, null),
				'code' => LightMetaProperty::fill(new LightMetaProperty(), 'code', null, 'string', null, 32, false, true, false, null, null),
				'autoLogin' => LightMetaProperty::fill(new LightMetaProperty(), 'autoLogin', 'auto_login', 'string', null, 32, false, true, false, null, null),
				'role' => LightMetaProperty::fill(new LightMetaProperty(), 'role', 'role_id', 'enumeration', 'Role', 8, true, false, false, 1, 3)
			);
		}
	}
?>