<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-09-21 11:00:44                         *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoProtoMailQueue extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'MailQueue', 8, true, true, false, null, null),
				'user' => LightMetaProperty::fill(new LightMetaProperty(), 'user', 'user_id', 'identifier', 'User', 8, true, false, false, 1, 3),
				'email' => LightMetaProperty::fill(new LightMetaProperty(), 'email', null, 'string', null, 256, true, true, false, null, null),
				'subject' => LightMetaProperty::fill(new LightMetaProperty(), 'subject', null, 'string', null, 256, true, true, false, null, null),
				'body' => LightMetaProperty::fill(new LightMetaProperty(), 'body', null, 'string', null, 4096, true, true, false, null, null),
				'created' => LightMetaProperty::fill(new LightMetaProperty(), 'created', null, 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'sent' => LightMetaProperty::fill(new LightMetaProperty(), 'sent', null, 'timestamp', 'Timestamp', null, false, true, false, null, null)
			);
		}
	}
?>