<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-09-21 11:00:44                         *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoMailQueue extends IdentifiableObject
	{
		protected $user = null;
		protected $userId = null;
		protected $email = null;
		protected $subject = null;
		protected $body = null;
		protected $created = null;
		protected $sent = null;
		
		/**
		 * @return User
		**/
		public function getUser()
		{
			if (!$this->user && $this->userId) {
				$this->user = User::dao()->getById($this->userId);
			}
			
			return $this->user;
		}
		
		public function getUserId()
		{
			return $this->userId;
		}
		
		/**
		 * @return MailQueue
		**/
		public function setUser(User $user)
		{
			$this->user = $user;
			$this->userId = $user->getId();
			
			return $this;
		}
		
		/**
		 * @return MailQueue
		**/
		public function setUserId($id)
		{
			$this->user = null;
			$this->userId = $id;
			
			return $this;
		}
		
		/**
		 * @return MailQueue
		**/
		public function dropUser()
		{
			$this->user = null;
			$this->userId = null;
			
			return $this;
		}
		
		public function getEmail()
		{
			return $this->email;
		}
		
		/**
		 * @return MailQueue
		**/
		public function setEmail($email)
		{
			$this->email = $email;
			
			return $this;
		}
		
		public function getSubject()
		{
			return $this->subject;
		}
		
		/**
		 * @return MailQueue
		**/
		public function setSubject($subject)
		{
			$this->subject = $subject;
			
			return $this;
		}
		
		public function getBody()
		{
			return $this->body;
		}
		
		/**
		 * @return MailQueue
		**/
		public function setBody($body)
		{
			$this->body = $body;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getCreated()
		{
			return $this->created;
		}
		
		/**
		 * @return MailQueue
		**/
		public function setCreated(Timestamp $created)
		{
			$this->created = $created;
			
			return $this;
		}
		
		/**
		 * @return MailQueue
		**/
		public function dropCreated()
		{
			$this->created = null;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getSent()
		{
			return $this->sent;
		}
		
		/**
		 * @return MailQueue
		**/
		public function setSent(Timestamp $sent)
		{
			$this->sent = $sent;
			
			return $this;
		}
		
		/**
		 * @return MailQueue
		**/
		public function dropSent()
		{
			$this->sent = null;
			
			return $this;
		}
	}
?>