<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2012-09-11 15:25:12                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoUser extends NamedObject
	{
		protected $surname = null;
		protected $email = null;
		protected $password = null;
		protected $phone = null;
		protected $created = null;
		protected $activated = null;
		protected $code = null;
		protected $autoLogin = null;
		
		public function getSurname()
		{
			return $this->surname;
		}
		
		/**
		 * @return User
		**/
		public function setSurname($surname)
		{
			$this->surname = $surname;
			
			return $this;
		}
		
		public function getEmail()
		{
			return $this->email;
		}
		
		/**
		 * @return User
		**/
		public function setEmail($email)
		{
			$this->email = $email;
			
			return $this;
		}
		
		public function getPassword()
		{
			return $this->password;
		}
		
		/**
		 * @return User
		**/
		public function setPassword($password)
		{
			$this->password = $password;
			
			return $this;
		}
		
		public function getPhone()
		{
			return $this->phone;
		}
		
		/**
		 * @return User
		**/
		public function setPhone($phone)
		{
			$this->phone = $phone;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getCreated()
		{
			return $this->created;
		}
		
		/**
		 * @return User
		**/
		public function setCreated(Timestamp $created)
		{
			$this->created = $created;
			
			return $this;
		}
		
		/**
		 * @return User
		**/
		public function dropCreated()
		{
			$this->created = null;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getActivated()
		{
			return $this->activated;
		}
		
		/**
		 * @return User
		**/
		public function setActivated(Timestamp $activated)
		{
			$this->activated = $activated;
			
			return $this;
		}
		
		/**
		 * @return User
		**/
		public function dropActivated()
		{
			$this->activated = null;
			
			return $this;
		}
		
		public function getCode()
		{
			return $this->code;
		}
		
		/**
		 * @return User
		**/
		public function setCode($code)
		{
			$this->code = $code;
			
			return $this;
		}
		
		public function getAutoLogin()
		{
			return $this->autoLogin;
		}
		
		/**
		 * @return User
		**/
		public function setAutoLogin($autoLogin)
		{
			$this->autoLogin = $autoLogin;
			
			return $this;
		}
	}
?>