<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-08-20 14:06:13                         *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoCity extends NamedObject
	{
		protected $latitude = null;
		protected $longitude = null;
		protected $parent = null;
		
		public function getLatitude()
		{
			return $this->latitude;
		}
		
		/**
		 * @return City
		**/
		public function setLatitude($latitude)
		{
			$this->latitude = $latitude;
			
			return $this;
		}
		
		public function getLongitude()
		{
			return $this->longitude;
		}
		
		/**
		 * @return City
		**/
		public function setLongitude($longitude)
		{
			$this->longitude = $longitude;
			
			return $this;
		}
		
		/**
		 * @return City
		**/
		public function getParent()
		{
			return $this->parent;
		}
		
		/**
		 * @return City
		**/
		public function setParent(City $parent)
		{
			$this->parent = $parent;
			
			return $this;
		}
		
		/**
		 * @return City
		**/
		public function dropParent()
		{
			$this->parent = null;
			
			return $this;
		}
	}
?>