<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-07-04 13:54:29                         *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoUnit extends NamedObject
	{
		protected $value = null;
		
		public function getValue()
		{
			return $this->value;
		}
		
		/**
		 * @return Unit
		**/
		public function setValue($value)
		{
			$this->value = $value;
			
			return $this;
		}
	}
?>