<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2012-08-29 19:43:48                     *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

	abstract class AutoUser extends NamedObject
	{
		protected $surname = null;
		protected $email = null;
		protected $password = null;
		protected $phone = null;
		protected $activated = false;
		protected $code = 'false';
		protected $autoLogin = 'false';
		
		public function getSurname()
		{
			return $this->surname;
		}
		
		/**
		 * @return User
		**/
		public function setSurname($surname)
		{
			$this->surname = $surname;
			
			return $this;
		}
		
		public function getEmail()
		{
			return $this->email;
		}
		
		/**
		 * @return User
		**/
		public function setEmail($email)
		{
			$this->email = $email;
			
			return $this;
		}
		
		public function getPassword()
		{
			return $this->password;
		}
		
		/**
		 * @return User
		**/
		public function setPassword($password)
		{
			$this->password = $password;
			
			return $this;
		}
		
		public function getPhone()
		{
			return $this->phone;
		}
		
		/**
		 * @return User
		**/
		public function setPhone($phone)
		{
			$this->phone = $phone;
			
			return $this;
		}
		
		public function getActivated()
		{
			return $this->activated;
		}
		
		public function isActivated()
		{
			return $this->activated;
		}
		
		/**
		 * @return User
		**/
		public function setActivated($activated = null)
		{
			Assert::isTernaryBase($activated);
			
			$this->activated = $activated;
			
			return $this;
		}
		
		public function getCode()
		{
			return $this->code;
		}
		
		/**
		 * @return User
		**/
		public function setCode($code)
		{
			$this->code = $code;
			
			return $this;
		}
		
		public function getAutoLogin()
		{
			return $this->autoLogin;
		}
		
		/**
		 * @return User
		**/
		public function setAutoLogin($autoLogin)
		{
			$this->autoLogin = $autoLogin;
			
			return $this;
		}
	}
?>