<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.10.99 at 2012-07-28 23:35:44                     *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class City extends AutoCity implements Prototyped, DAOConnected
	{
		/**
		 * @return City
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return CityDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('CityDAO');
		}
		
		/**
		 * @return ProtoCity
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoCity');
		}
		
		const NICOSIA	= 1;
		const LARNAKA	= 2;
		const LIMASSOL	= 3;
		const PAPHOS	= 4;
		const AYANAPA	= 5;
		
		public function getDisplayName()
		{
			return $this->getName();
		}
	}
?>