<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-07-01 16:43:04                         *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class FeatureType extends AutoFeatureType implements Prototyped, DAOConnected
	{
		/**
		 * @return FeatureType
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return FeatureTypeDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('FeatureTypeDAO');
		}
		
		/**
		 * @return ProtoFeatureType
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoFeatureType');
		}
		
		const AREA		= 10;
		const PRICE		= 20;
		const BEDROOMS	= 30;
		const TOYLETS	= 40;
		const BALCONS	= 50;
		const LEVELS	= 60;
		const PARKING	= 70;
		const COVERED_PARKING	= 80;
		const GARDEN	= 90;
		const BARBEQUE	= 100;
		const POOL		= 110;
		const GARAGE	= 120;
		const KITCHENS	= 130;
		const STORAGE	= 150;
		const LAUNDRY	= 160;
		const FURNITURE	= 170;
		const FIREPLACE	= 180;
		const CELLAR	= 190;
		const ATTIC		= 200;
		const ELEVATOR	= 210;
		const FLOOR		= 220;
		const SEA_VIEW	= 230;
		const MOUNTAIN_VIEW = 240;
	}
?>