<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-08-20 14:10:54                         *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class FeatureType extends AutoFeatureType implements Prototyped, DAOConnected
	{
		/**
		 * @return FeatureType
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return FeatureTypeDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('FeatureTypeDAO');
		}
		
		/**
		 * @return ProtoFeatureType
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoFeatureType');
		}
		
		const INDOOR		= 0x0001;
		const OUTDOOR	= 0x0002;

		// MOST IMPORTAT FEATURES
		const PRICE		= 1;
		const AREA		= 2;
		const BEDROOMS	= 3;
		const TOYLETS	= 4;
		const CAR_PLACES= 7;	// number of parking places

		public function getDisplayName()
		{
			return ucwords($this->getName());
		}
	}
?>