<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-07-01 16:43:04                         *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class FeatureType extends AutoFeatureType implements Prototyped, DAOConnected
	{
		/**
		 * @return FeatureType
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return FeatureTypeDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('FeatureTypeDAO');
		}
		
		/**
		 * @return ProtoFeatureType
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoFeatureType');
		}
		
		const AREA		= 1;
		const PRICE		= 2;
		const BEDROOMS	= 3;
		const TOYLETS	= 4;
		const BALCONS	= 5;
		const LEVELS	= 6;
		const PARKING	= 7;
		const COVERED_PARKING	= 8;
		const GARDEN	= 9;
		const BARBEQUE	= 10;
		const POOL		= 11;
		const GARAGE	= 12;
		const KITCHENS	= 13;
		const STORAGE	= 15;
		const LAUNDRY	= 16;
		const FURNITURE	= 17;
		const FIREPLACE	= 18;
		const CELLAR	= 19;
		const ATTIC		= 20;
		const ELEVATOR	= 21;
		const FLOOR		= 22;
		const SEA_VIEW	= 23;
		const MOUNTAIN_VIEW = 24;
	}
?>