<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-09-11 16:00:25                         *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class MailQueue extends AutoMailQueue implements Prototyped, DAOConnected
	{
		/**
		 * @return MailQueue
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return MailQueueDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('MailQueueDAO');
		}
		
		/**
		 * @return ProtoMailQueue
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoMailQueue');
		}
		
		// your brilliant stuff goes here
	}
?>