<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-07-01 16:43:04                         *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class OfferType extends Enumeration
	{
		const OFFER_BUY		= 1;
		const OFFER_SELL	= 2;
		const OFFER_RENT	= 3;
		const OFFER_LEASE	= 4;

		protected $names = array(
			self::OFFER_BUY		=> 'buy',
			self::OFFER_SELL	=> 'sell',
			self::OFFER_RENT	=> 'rent',
			self::OFFER_LEASE	=> 'lease',
		);
	}
?>