<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-07-01 16:43:04                         *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class Property extends AutoProperty implements Prototyped, DAOConnected
	{
		/**
		 * @return Property
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return PropertyDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('PropertyDAO');
		}
		
		/**
		 * @return ProtoProperty
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoProperty');
		}
		
		// your brilliant stuff goes here
	}
?>