<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.9 at 2012-07-01 16:43:04                         *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class PropertyType extends Enumeration
	{
		const ROOM			= 1;
		const FLAT			= 2;
		const APPARTMENT	= 3;
		const HOUSE			= 4;

		protected $names = array(
			self::ROOM			=> 'room',
			self::FLAT			=> 'flat',
			self::APPARTMENT	=> 'appartment',
			self::HOUSE			=> 'house',
		);
	}
?>