<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2012-09-21 10:59:58                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

	final class Role extends Enumeration
	{
		const GUEST			= 1;
		const USER			= 2;
		const MODERATOR		= 3;
		const ADMINISTRATOR	= 4;

		protected $names = array(
			self::GUEST			=> 'guest',
			self::USER			=> 'user',
			self::MODERATOR		=> 'moderator',
			self::ADMINISTRATOR	=> 'admninstrator',
		);

		public static function guest()
		{
			return new self(self::GUEST);
		}

		public static function user()
		{
			return new self(self::USER);
		}
	}
?>